name: strings_extension
version: 3.1.2
documentation: https://strings.onepub.dev
description: Large collection of String functions aimed at extending the String class whilst providing safer methods for working with nullable Strings.
repository: https://github.com/yenderlobo10/strings-extension.git
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  characters: ^1.3.0
  unicode: ^0.3.1
dev_dependencies:
  lint_hard: ^4.0.0
  test: ^1.0.0
