name: strings_extension
version: 2.0.3
documentation: https://strings.onepub.dev
description: Provides a set of String related aimed at extending the core String class and provide safer methods for working with nullable strings and strings in general.
repository: https://github.com/yenderlobo10/strings-extension.git
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  characters: ^1.3.0
  unicode: ^0.3.1
dev_dependencies: 
  lint_hard: ^4.0.0
  test: ^1.0.0
